version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - medical-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: medical-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mvc
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf  # add this line
    networks:
      - medical-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: medical-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - medical-network

volumes:
  db_data:

networks:
  medical-network:
